### ISSUE TITLE
Read a blog post about how to add Rector to a site

### ISSUE THREAD

**Issue by shaal** [palantirnet/drupal-rector#10]
As a developer, I want to read a blog post on Palantir.net about how to add Rector to my site, so that I can use the tool.

### Implementation notes
We should have already added this to confluence / internal tools and the blog post might provide that as an easy option for people looking to try the tool.

**Comment by damontgomery** [comment]
We are no longer tracking these types of tasks here. For specific issues see Drupal.org.
