### ISSUE TITLE
Identify high priority deprecated functions

### ISSUE THREAD

**Issue by shaal** [palantirnet/drupal-rector#12]
Using the following resources -

**Top 15 errors across all drupal.org projects**
https://dev.acquia.com/drupal9/deprecation_status/graphs

**Deprecations by module popularity**
https://dev.acquia.com/drupal9/deprecation_status

**All deprecated APIs in Drupal 8**
https://api.drupal.org/api/drupal/8.8.x

**Comment by damontgomery** [comment]
High priority issues have been created on Drupal.org.
