### ISSUE TITLE
Windows path backslashes: Ambiguous class Drupal\action\ActionAddForm resolution

### ISSUE THREAD

**Issue by Ambient-Impact** [palantirnet/drupal-rector#124]
Hi there. I'm trying to run this on a Windows laptop and it keeps throwing the following error for multiple modules I've tried:

```
Rector v0.7.29
Config file: C:/Windows/Temp/upgrade_rector/upgrade_rector.yml


In RobotLoader.php line 186:

  Ambiguous class Drupal\action\ActionAddForm resolution; defined in E:/Web/A
  mbient.Impact/Web/drupal/core\modules\action\src\ActionAddForm.php and in E
  :/Web/Ambient.Impact/Web/drupal/core/modules\action\src\ActionAddForm.php.


process [-n|--dry-run] [-a|--autoload-file AUTOLOAD-FILE] [--match-git-diff] [-o|--output-format [OUTPUT-FORMAT]] [--no-progress-bar] [--output-file OUTPUT-FILE] [--cache-debug] [--clear-cache] [--] [<source>...]
```

After some confusion about why it would list the same file with the exact same path twice, I noticed that there's a different slash in one compared to the other (```core\modules``` versus ```core/modules```), which leads me to believe it's got something to do with the backslashes used on Windows versus forward slashes on *nix systems and not normalizing that somehow.

Edit: seems to be a known issue [reported in upgrade_rector](https://www.drupal.org/project/upgrade_rector/issues/3152937).

**Comment by damontgomery** [comment]
Thanks for the detailed issue info and sorry for the issues.

I don't know that any of us have tested this on Windows, but you might try updating your `rector.yml` file and switching the slashes. See some of the examples like https://github.com/palantirnet/drupal-rector/blob/master/rector-config-web-dir.yml.

**Comment by Ambient-Impact** [comment]
Thanks for the reply. We did that in the linked issue and that fixed the problem. That said, it would be great to have this fixed in drupal-rector itself if possible. Maybe paths could be run through [`realpath()`](https://www.php.net/manual/en/function.realpath.php) or something similar so PHP can fix that for us?

**Comment by agentrickard** [comment]
This issue has been moved to https://www.drupal.org/project/rector/issues/3219157
