### ISSUE TITLE
Problem with MigrationInterface

### ISSUE THREAD

**Issue by FlorentTorregrosa** [palantirnet/drupal-rector#132]
On:
* Drupal 9.1.4
* Drupal-rector 0.5.6
* Rector: 0.7.29
* PHP 7.4

I have the following error when scanning my website:
```
Fatal error: require(): Failed opening required 'app/core/modules/migrate/src/Plugin/MigrationInterface.php' (include_path='/project/vendor/pear/archive_tar:/project/vendor/pear/console_getopt:/project/vendor/pear/pear-core-minimal/src:/project/vendor/pear/pear_exception:/project/vendor/pear/archive_tar:/project/vendor/pear/console_getopt:/project/vendor/pear/pear-core-minimal/src:/project/vendor/pear/pear_exception:.:/usr/local/lib/php') in phar:///project/vendor/rector/rector-prefixed/rector/vendor/nette/robot-loader/src/RobotLoader/RobotLoader.php on line 92
```

I have a custom module with some migration process plugins, and I can't find why rector can't opened the required classes/interfaces.

Thanks for any help.

**Comment by shaal** [comment]
@FlorentTorregrosa thank you for reporting this.
Drupal-Rector currently works on Drupal8, and can fix deprecations to prepare websites for Drupal9.
We have an active PR #117, that will work on Drupal9, and will fix deprecations to prepare websites for Drupal10.

For now, it is recommended to run Drupal-Rector on Drupal8, before upgrading to Drupal9.

**Comment by FlorentTorregrosa** [comment]
Thanks @shaal for the quick reply.

I run rector on my website to check regularly for deprecations, on whatever version it is.

No urgency, for the moment I have just excluded those files from the check, I will wait for the PR for Drupal 9 compatibility, I just wanted to report the bug.

Cheers :)

**Comment by tharna** [comment]
I have this exact same issue with Drupal 8.9.13

**Comment by akramzairig** [comment]
Same issue here 
Error message : `Fatal error: require(): Failed opening required 'core/modules/migrate/src/Plugin/MigrateIdMapInterface.php' (include_path='/var/www/html/vendor/pear/archive_tar:/var/www/html/vendor/pear/console_getopt:/var/www/html/vendor/pear/pear-core-minimal/src:/var/www/html/vendor/pear/pear_exception:.:/usr/local/lib/php') in phar:///var/www/html/vendor/rector/rector-prefixed/rector/vendor/nette/robot-loader/src/RobotLoader/RobotLoader.php on line 92`

**Comment by shaal** [comment]
@tharna and @akramzairig Thank you for reporting this.
Can you write the list of steps to reproduce this problem? Like what modules should be installed, what is the drupal-rector command you are running?

**Comment by agentrickard** [comment]
https://www.drupal.org/project/rector/issues/3219156 is the proper place to track the Drupal 9 compatibility issue.
