### ISSUE TITLE
Upgrade to Rector 0.10

### ISSUE THREAD

**Issue by mglaman** [palantirnet/drupal-rector#133]
I'm working on the upgrade. 

Notes:

* There PR #122. This is for 0.8 and the source branch has since been deleted.
* The conflict is on `DrupalRector\Rector\Deprecation\EntityDeleteMultipleRector:~` which must have been added sometime between the PR being start.

**Comment by agentrickard** [comment]
Committed and filed as https://www.drupal.org/project/rector/issues/3219155
