### ISSUE TITLE
Leverage webflo/drupal-finder to discover Drupal and reduce number of config files to maintain

### ISSUE THREAD

**Issue by mglaman** [palantirnet/drupal-rector#135]
We could use `webflo/drupal-finder` package to determine where Drupal is located and not need `rector-config-docroot-dir.php` or `rector-config-web-dir.php`. It could dynamically determine, which lowers maintenance cost.

**Comment by mglaman** [comment]
This is blocked #134 which moves config to PHP files

**Comment by agentrickard** [comment]
This has been implemented and filed at https://www.drupal.org/project/rector/issues/3219153
