### ISSUE TITLE
Upgrading a d7 module

### ISSUE THREAD

**Issue by ugintl** [palantirnet/drupal-rector#137]
I want to upgrade a d7 module. Can rector help? I have tried drupalmoduleupgrader module, but it is getting errors and not upgrading.

**Comment by damontgomery** [comment]
@ugintl,

Unfortunately it won't really help.

This module will update deprecations in the current version of Drupal and right now this means updating deprecations in D8 code to be compatible with D8 and D9.

D7 to D8 is a very large shift and it is challenging and often very manual.

There are some `quick` ways to upgrade D7 to D8 that include using functions that are deprecated in D9. So, you may be able to use Drupal Rector to update D8 working code that was done with these quick methods that will no longer work in D9.
