### ISSUE TITLE
Add custom binary to run rector with default config

### ISSUE THREAD

**Issue by joeparsons** [palantirnet/drupal-rector#139]
During the Drupal 10 readiness Friday contribution event at DrupalCon today @shaal suggested that it would be useful to add something like a script that runs rector with a default configuration to make it easier for people to get started using it.

@mglaman suggested this could be a custom binary for drupal rector (similar to the one used in his [drupal-check project](https://github.com/mglaman/drupal-check)) that checks for a rector.php config and uses that if present or falls back to a default configuration.

**Comment by agentrickard** [comment]
Moved to https://www.drupal.org/project/rector/issues/3219162
