### ISSUE TITLE
Encourage Drupal 8.x users to upgrade to the most recent version of Drupal 8 before running Drupal Rector.

### ISSUE THREAD

**Issue by damontgomery** [palantirnet/drupal-rector#142]
TLDR: Drupal Rector tries to find some classes that exist only in newer versions of core.

It's a lot of work to try to accommodate various older versions of Drupal core, so we could support the latest and encourage people to upgrade to run Rector.

Discussed in #134.

**Comment by damontgomery** [comment]
See https://github.com/palantirnet/drupal-rector/pull/134#issuecomment-821547909

**Comment by shaal** [comment]
An old idea we had, was add CLI command, that can receive as parameter (or perhaps can look for it automatically), minimum and maximum Drupal versions to support, so it will only run the specific sets of Rector rules.

**Comment by damontgomery** [comment]
Since the configuration is PHP now... we may be able to do... ANYTHING! :)

**Comment by agentrickard** [comment]
Moved to https://www.drupal.org/project/rector/issues/3219159
