### ISSUE TITLE
Run automated PhpUnit tests

### ISSUE THREAD

**Issue by damontgomery** [palantirnet/drupal-rector#145]
Rector (rector/rector) includes PhpUnit tests and ways for us to develop our own tests that extend those tests.

During an upgrade to support 0.10.x, @mglaman was able to implement the framework, but I (Dan) was able to get it to run locally.

Please see https://github.com/palantirnet/drupal-rector/pull/134.

Matt got a lot of value from using PhpUnit during this major upgrade and if we can iron out a few of the remaining pieces and add documentation, the tool could be very useful for developers.

**Comment by agentrickard** [comment]
This issue has been moved to https://www.drupal.org/project/rector/issues/3217424
