### ISSUE TITLE
Run PhpStan static analysis

### ISSUE THREAD

**Issue by damontgomery** [palantirnet/drupal-rector#146]
Can we have PhpStan run for development of the tool?

@mglaman was able to get this working as part of the upgrade to 0.10.x in https://github.com/palantirnet/drupal-rector/pull/134.

Can we take pieces of that and add documentation about how to use it?

Matt said this was very useful for him during the upgrade and it would be a good tool for developers to have.

**Comment by agentrickard** [comment]
Moved to https://www.drupal.org/project/rector/issues/3219160
