### ISSUE TITLE
Test and document Symfony upgrades through existing Rectors

### ISSUE THREAD

**Issue by shaal** [palantirnet/drupal-rector#3]
From @goba
https://dev.acquia.com/drupal9/deprecation_status/errors?message=Symfony
has some false positives but also some examples
eg. https://dev.acquia.com/drupal9/deprecation_status/errors/4905

`Call to deprecated method getArguments() of class Symfony\Component\HttpKernel\Controller\ControllerResolverInterface: This method is deprecated as of 3.1 and will be removed in 4.0. Please use the {@see ArgumentResolverInterface} instead.`

2 projects affected or this in devel module https://dev.acquia.com/drupal9/deprecation_status/errors/1923

or this in backup_migrate: https://dev.acquia.com/drupal9/deprecation_status/errors?project=backup_migrate%204.1%20

Additional info in this blog post:
https://www.tomasvotruba.com/blog/2019/02/28/how-to-upgrade-symfony-2-8-to-3-4/#forget-upgrade-md

**Comment by agentrickard** [comment]
Closing as outdated.
