### ISSUE TITLE
New Rector for renaming Drupal::service() calls

### ISSUE THREAD

**Issue by dbuytaert** [palantirnet/drupal-rector#46]
I wrote a quick Rector that renames `Drupal::service()` calls.  

I focused on renaming of the path alias services (https://www.drupal.org/node/3092086), but others could be added in time.

For now, I attached it as a ZIP-file but can submit a pull request later.  It's my first ever Rector, so feedback welcome.

Thanks for creating Drupal Rector! This will be great for Drupal 9. 

[RenameDrupalServiceRector.php.zip](https://github.com/palantirnet/drupal-rector/files/4499967/RenameDrupalServiceRector.php.zip)

**Comment by damontgomery** [comment]
Thanks!

Please see https://github.com/palantirnet/drupal-rector/pull/47 for progress for this.

I'm not familiar with attributing the commits to other people, so I apologize if that is an issue. We can recreate that branch if that would help there.

**Comment by dbuytaert** [comment]
Thank you! The refactoring looks good too.  👍
