### ISSUE TITLE
Run Drupal rector against an example module

### ISSUE THREAD

**Issue by shaal** [palantirnet/drupal-rector#5]
As a developer, given I am developing rectors, I want to work with an example module, so that I don’t have to create tests myself.

### Implementation notes
Can we create a Drupal module in the drupal8-rector project that can be used to test all of the Drupal deprecations?

If the rector system will not run without all of the dependencies, we may want to symlink this inside the sandbox and run it from there.

**Comment by damontgomery** [comment]
This has been in the project for a while. Closing.
