### ISSUE TITLE
Run current community rectors

### ISSUE THREAD

**Issue by shaal** [palantirnet/drupal-rector#6]
As a developer, I want to run the currently available Drupal 8 rectors, so that I get the most feedback about my code.

### Implementation notes
There are several open PRs against the upstream drupal8-rector repository. Can we merge that code into our fork so that we have those updates?

**Comment by damontgomery** [comment]
We are reviewing them as we work on other tasks. Closing for now. If someone wants to revisit it, they can comment here.
