### ISSUE TITLE
Got iconv errors in Alpine based Docker image

### ISSUE THREAD

**Issue by back-2-95** [palantirnet/drupal-rector#66]
And got rid off the error with help of
https://github.com/nunomaduro/phpinsights/issues/43

So this could be put to some FAQ section or something like that.

**Comment by shaal** [comment]
I am not familiar with Apline based Docker images.
Can you create a PR with the text that we should add to FAQ?

**Comment by back-2-95** [comment]
@shaal I created PR #67
