### ISSUE TITLE
Read a blog post about how to update [INSERT HERE] deprecated functionality using a Rector

### ISSUE THREAD

**Issue by shaal** [palantirnet/drupal-rector#7]
As a developer, I want to read a blog post on Palantir.net about how to update [INSERT HERE] deprecated functionality manually and using a Rector, so that I can understand how to update code and use the new feature.

- I want to read example code that shows the deprecated feature
- I want to read example code of the updated feature
- I want to read an explanation of why how this is changed
- I want to read what the Rector covers
- I want to read what the Rector does not cover, such as dependency injection

### Implementation notes

Drupal change records contain examples we may be able to re-use. We may also pull out some specifics and provide links there. This blog post should be useful for people that want to understand how to make the changes manually and also provide information on what the automated tool does.

**Comment by damontgomery** [comment]
We are tracking issues on Drupal.org and no longer need this template.
