### ISSUE TITLE
Created Docker Image to run drupal-rector

### ISSUE THREAD

**Issue by back-2-95** [palantirnet/drupal-rector#72]
Docker image:
https://hub.docker.com/repository/docker/druidfi/drupal-rector

And Gist as an example:
https://gist.github.com/back-2-95/fe39495086cdace14d521454451432f7

Basically I say which custom OR contrib module to check and output --dry-run output.

**Comment by damontgomery** [comment]
Thanks, @back-2-95.

Is there a reason the Dockerfile is hidden? I'm curious what's involved in creating this container.

**Comment by back-2-95** [comment]
Hi & sorry, just pushed the image from local.

Here is the Dockerfile
https://github.com/druidfi/docker-images/blob/master/drupal/rector/Dockerfile

**Comment by damontgomery** [comment]
Thanks for the example @back-2-95.

It's cool to see this installed alongside a website. I haven't tried doing that, but your example of installing Rector globally makes sense to me I think.

We had challenges originally trying to figure out if installing this separately would be a good idea, particularly around autoloading issues we were having.

I think the simplest setup may still be to install the project as a dev dependency, but I think this is a good option for people who want to go this route.

I'm not sure if we have the capacity to support this setup, so I'm not sure exactly what the next steps might be.

Thanks again for the example! I think it will definitely help someone else if they are trying to do something similar and we may revisit it later.

**Comment by back-2-95** [comment]
Thanks @damontgomery :)

We use tools like this when it's easiest way to our developers to use. E.g. we use phpcs similar way. And ofc one benefit is that you don't need to add it to composer.json (and thus making it's own constraints and requirements for that project). Another example is PHPUnit where we NOT use this kind of way as tests in your project are depending on PHPUnit. That said 

We internally use Makefiles to "create" these commands for us, but it could also be added e.g. to Composers "scripts" section for a project.

I'll be updating that image when needed as we're also gonna be updating our sites to Drupal 9.

**Comment by damontgomery** [comment]
Thanks for the context!

**Comment by agentrickard** [comment]
There is no clear action to take here.
