### ISSUE TITLE
Update [INSERT HERE] deprecated functionality using a Rector

### ISSUE THREAD

**Issue by shaal** [palantirnet/drupal-rector#8]
As a developer, given my code has [INSERT HERE] deprecated feature, I want to have it updated automatically using Rector.

- I want the code to be updated using a non-deprecated method
- Given there are multiple ways the deprecation could be used, I want all versions of that deprecation to be updated
- (stretch goal) I want in-code examples
- (stretch goal) I want in-code references to change logs

### Implementation notes

Testing steps should include sample code that can be used for testing.

For the first version, we do not need to use the best way to replace the code, just one that is viable. For example, dependency injection might be the preferred way to add some of these features, but static calls may be easier to implement initially.

**Comment by damontgomery** [comment]
We are tracking issues publicly on Drupal.org now. This template is no longer needed.
