### ISSUE TITLE
Read a blog post about how to create a Rector

### ISSUE THREAD

**Issue by shaal** [palantirnet/drupal-rector#9]
As a developer, I want to read a blog post on Palantir.net about how to create a Rector for Drupal.

- I want to understand the basics of how to create a Rector
- I want to understand how to create one for Drupal
- I want to understand how to find change records for a deprecated feature
- I want to know where to submit my work

### Implementation notes
There is some existing documentation about how to create a rector, terminology, etc. It might be helpful to repeat the high level items for that and then reference the existing blog posts / documentation.

**Comment by damontgomery** [comment]
We are no longer tracking these types of tasks here. For specific issues see Drupal.org.
