### ISSUE TITLE
Add special exclude for upgrade_rector fatal error test directory 

### ISSUE THREAD

**Issue by shaal** [palantirnet/drupal-rector#96]
Based on Drupal issue https://www.drupal.org/project/rector/issues/3136080

Add the following code to rector.yml
```yml
exclude_paths:
  - 'modules/contrib/upgrade_status/tests/modules/upgrade_status_test_error/fatal.php'
```

**Comment by goba** [comment]
As shown in the d.o issues, a shorter more universal match could be used so it is less prone to not applying if the module was installed elsewhere.

**Comment by goba** [comment]
```
  exclude_paths:
    - '*/upgrade_status/tests/modules/*'
```

I don't think this would match for any false positives.

**Comment by damontgomery** [comment]
@goba, this was added in https://github.com/palantirnet/drupal-rector/blob/master/rector.yml.
