### ISSUE TITLE
Rector binary is not installed

### ISSUE THREAD

**Issue by rudolfbyker** [palantirnet/drupal-rector#97]
I followed the instructions at https://github.com/palantirnet/drupal-rector#installation to install rector:

```
composer require palantirnet/drupal-rector --dev
```

This gave me version `0.5.4`, but with the following warning:

```
Skipped installation of bin rector for package rector/rector-prefixed: file not found in package
Skipped installation of bin rector.phar for package rector/rector-prefixed: file not found in package
```

So I can't run it, because there is no `vendor/bin/rector` binary.

The same thing happens when installing the latest master:

```
composer require --dev "palantirnet/drupal-rector:dev-master"
```

**Comment by damontgomery** [comment]
Thanks for opening this. I'm not able to reproduce the issue and not really sure how to proceed.

Can you try again and / or provide some more information.

We have an automated test that downloads the latest version whenever we do a commit and that's passing, https://github.com/palantirnet/drupal-rector/runs/710379731?check_suite_focus=true.

I also created a composer package locally with nothing in it and did the `composer require palantirnet/drupal-rector --dev` command. With `"minimum-stability": "dev",` in the composer.json file, everything installed fine and the binaries are in vendor/bin.

**Comment by shaal** [comment]
I ran the command `composer require palantirnet/drupal-rector --dev` in a new empty directory, and got a warning that it cannot be installed because 
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for palantirnet/drupal-rector ^0.5.4 -> satisfiable by palantirnet/drupal-rector[0.5.4].
    - palantirnet/drupal-rector 0.5.4 requires rector/rector-prefixed dev-master#cd10d7f -> satisfiable by rector/rector-prefixed[dev-master] but these conflict with your requirements or minimum-stability.
```

@rudolfbyker The error you are seeing is probably caused by something else (but I do not know yet what it is).
We need to be able to replicate the scenario you are seeing.

Can you share your `composer.json` file?
What operating system you are using?
Are you using Docker in your setup?

Can you try removing all content of `vendor` directory (`rm -rf vendor`) and run composer again?

**Comment by damontgomery** [comment]
@shaal , the error you mentioned can be resolved by adding this to `composer.json`

`"minimum-stability": "dev",`

**Comment by rudolfbyker** [comment]
> Can you share your composer.json file?

Unfortunately, no, since the project is proprietary. If I start a new project and just copy the composer.json and composer.lock from the old project, rector gets installed normally.

> What operating system you are using?

Linux Mint 19.1 Tessa

> Are you using Docker in your setup?

No.

> Can you try removing all content of vendor directory (rm -rf vendor) and run composer again?

Yes, that solved the problem. So maybe it's a bug in composer (which I won't be able to reproduce, since the old vendor dir is now gone). Or it was a network issue (not improbably, since my ISP, Vodacom, hijacks unencrypted HTTP 404 responses to serve up a silly portal page with code 200. This has confused up some other package managers in the past, notably `apt`).
